# Generated by Django 6.0 on 2025-12-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labor Items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['invoice'], name='invoices_la_invoice_6ca848_idx'), models.Index(fields=['description'], name='invoices_la_descrip_230130_idx')],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['invoice'], name='invoices_pa_invoice_c534a1_idx'), models.Index(fields=['description'], name='invoices_pa_descrip_c4b9d7_idx')],
            },
        ),
    ]
