# Generated by Django 6.0 on 2025-12-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_amount_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labor',
            options={'ordering': ['position'], 'verbose_name': 'Labor', 'verbose_name_plural': 'Labor Items'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['position'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='labor',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
