# Generated by Django 6.0 on 2025-12-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_labor_options_alter_part_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=8.25, max_digits=5),
        ),
    ]
