# Generated by Django 6.0 on 2025-12-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255, unique=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_time', models.DateTimeField()),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
