# Generated by Django 6.0 on 2025-12-30 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 30, 11, 50, 44, 19470, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
