# Generated by Django 6.0 on 2026-03-25 23:44

import companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(unique=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(blank=True, max_length=64)),
                ('admin_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#2f80ed', max_length=20)),
                ('accent_color', models.CharField(default='#215199ff', max_length=20)),
                ('alert_color', models.CharField(default='#dc2626', max_length=20)),
                ('warning_color', models.CharField(default='#f59e0b', max_length=20)),
                ('success_color', models.CharField(default='#22c55e', max_length=20)),
                ('business_hours', models.JSONField(default=companies.models.default_business_hours)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['zip_code'], name='companies_c_zip_cod_7f7e81_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['city', 'state'], name='companies_c_city_6d9404_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('user', 'company')},
        ),
    ]
