# Generated by Django 6.0 on 2025-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('A', 'Appointment'), ('I', 'Invoice'), ('S', 'System'), ('M', 'Message'), ('G', 'General'), ('R', 'Reminder'), ('P', 'Payment'), ('U', 'Update')], default='S', max_length=1, null=True),
        ),
    ]
