# Generated by Django 6.0 on 2025-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='msgs_messag_sender_7d9c02_idx',
            old_name='msgs_messag_sender__f9e1f2_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='msgs_messag_recipie_f86daf_idx',
            old_name='msgs_messag_recipie_7f3aa2_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=128),
        ),
    ]
