# Generated by Django 6.0 on 2025-12-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_rename_msgs_messag_sender__f9e1f2_idx_msgs_messag_sender_7d9c02_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='msgs_messag_recipie_f86daf_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
