# Generated by Django 6.0 on 2026-03-25 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('msgs', '0004_remove_message_msgs_messag_recipie_f86daf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='companies.company'),
        ),
    ]
